# Generated by Django 6.0.5 on 2026-05-14 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('form_type', models.CharField(choices=[('ug', 'Undergraduate'), ('pg', 'Postgraduate (GS-10)')], max_length=5)),
                ('description', models.TextField(blank=True)),
                ('fields_schema', models.JSONField(blank=True, default=list, help_text='JSON schema defining form fields')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_supervisor', models.BooleanField(default=False, help_text='PG forms requiring supervisor approval')),
                ('requires_hod', models.BooleanField(default=False, help_text='Forms requiring HOD approval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_templates', to='university.department')),
            ],
            options={
                'verbose_name': 'Form Template',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='forms/submissions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('supervisor_approved', models.BooleanField(blank=True, null=True)),
                ('hod_approved', models.BooleanField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='form_manager.formtemplate')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
