# Generated by Django 6.0.5 on 2026-05-14 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QECFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('teaching_rating', models.PositiveIntegerField(default=3, help_text='1-5 rating')),
                ('content_rating', models.PositiveIntegerField(default=3)),
                ('assessment_rating', models.PositiveIntegerField(default=3)),
                ('overall_rating', models.PositiveIntegerField(default=3)),
                ('comments', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('semester', models.CharField(blank=True, max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qec_feedback', to='courses.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qec_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QEC Feedback',
                'verbose_name_plural': 'QEC Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
